### ISSUE TITLE
Privacy link is not correct

### ISSUE THREAD

**Issue by rajyraman** [cloudsmithconsulting/cds-for-code#9]
The link on the privacy notice is incorrect. https://github.com/cloudsmith-consulting/cds-for-code/privacy.md does not resolve.

![image](https://user-images.githubusercontent.com/5035266/73218913-0956ff00-41af-11ea-9eba-1fa0915b9931.png)

**Comment by CloudSmithBrandon** [comment]
Thank you for the report.  We have added this to the next sprint's backlog and will address in 0.9.0.

**Comment by CloudSmithBrandon** [comment]
We have released 0.8.11 to the Marketplace today, which addresses this issue.  Thank you for the report.
